### PR TITLE
Add support for Azure CLI authentication

### PR DESCRIPTION
**Pull request by williamoconnorme**
This pull request adds support for authenticating to Azure using an Azure CLI authentication token. This will enhance local development with this module while also enabling certain CI/CD systems that already use the AZ CLI for authenticating with other terraform providers such as `azurerm` or `aztfy` to continue to use the same authentication mechanism when working with Azure.

Authenticating with `NewClientCredentialsConfig` remains as the preferred authentication flow when  `client_id`, `client_secret` and `tenant_id` are set to retain backwards compatibility.

This pull request also removes the vendor directory and adds it to gitignore as the contents of this directory are created during build.

### CODE REVIEW

**Comment by williamoconnorme** [comment]
Hi @tiwood @tmeckel , I'm not sure how active this repository is but if still under development would you be able to review

**Comment by tiwood** [comment]
Hi @williamoconnorme,

I'll check your PR soon and get back to you. Thanks for the contribution

**Comment by sikksakk** [comment]
any hope of getting this merged @tiwood ?

**Comment by tiwood** [comment]
Hi,

sorry for the radio silence. I finally had the time to update the SDK and was able to introduce support for `AzureDefaultCredential` which no allows you to authenticate using Azure CLI, Managed Identity, AZURE_ Environment Vars and the default client credentials flow.

https://registry.terraform.io/providers/tiwood/azresourcegraph/latest/docs

**Pull request closed without merging**
